numeroCasosLocalizacaoPrimaria <- function(dfDados){
  library(ggplot2)

  df<-aggregate(data.frame(NroCasos = dfDados$LOCTUDET), list(LOCTUDET = dfDados$LOCTUDET), length)

  df$LOCTUDET <- converterFatorParaCaracter(df$LOCTUDET)

  df$LOCTUDET[df$LOCTUDET == "C00"] <- "C00 - Neoplasia Maligna do Lábio"
  df$LOCTUDET[df$LOCTUDET == "C01"] <- "C01 - Neoplasia Maligna da Base da Língua"
  df$LOCTUDET[df$LOCTUDET == "C02"] <- "C02 - Neoplasia Maligna de Outras Partes e de Partes Não Especificadas da Língua"
  df$LOCTUDET[df$LOCTUDET == "C03"] <- "C03 - Neoplasia Maligna da Gengiva"
  df$LOCTUDET[df$LOCTUDET == "C04"] <- "C04 - Neoplasia Maligna do Assoalho da Boca"
  df$LOCTUDET[df$LOCTUDET == "C05"] <- "C05 - Neoplasia Maligna do Palato"
  df$LOCTUDET[df$LOCTUDET == "C06"] <- "C06 - Neoplasia Maligna de Outras Partes e de Partes Não Especificadas da Boca"
  df$LOCTUDET[df$LOCTUDET == "C07"] <- "C07 - Neoplasia Maligna da Glândula Parótida"
  df$LOCTUDET[df$LOCTUDET == "C08"] <- "C08 - Neoplasia Maligna de Outras Glândulas Salivares Maiores e as Não Especificadas"
  df$LOCTUDET[df$LOCTUDET == "C09"] <- "C09 - Neoplasia Maligna da Amígdala"
  df$LOCTUDET[df$LOCTUDET == "C10"] <- "C10 - Neoplasia Maligna da Orofaringe"
  df$LOCTUDET[df$LOCTUDET == "C11"] <- "C11 - Neoplasia Maligna da Nasofaringe"
  df$LOCTUDET[df$LOCTUDET == "C12"] <- "C12 - Neoplasia Maligna do Seio Piriforme"
  df$LOCTUDET[df$LOCTUDET == "C13"] <- "C13 - Neoplasia Maligna da Hipofaringe"
  df$LOCTUDET[df$LOCTUDET == "C14"] <- "C14 - Neoplasia Maligna de Outras Localizações e de Localizações Mal Definida, do Lábio, Cavidade Oral e Faringe"
  df$LOCTUDET[df$LOCTUDET == "C15"] <- "C15 - Neoplasia Maligna do Esôfago"
  df$LOCTUDET[df$LOCTUDET == "C16"] <- "C16 - Neoplasia Maligna do Estômago"
  df$LOCTUDET[df$LOCTUDET == "C17"] <- "C17 - Neoplasia Maligna do Intestino Delgado"
  df$LOCTUDET[df$LOCTUDET == "C18"] <- "C18 - Neoplasia Maligna do Cólon"
  df$LOCTUDET[df$LOCTUDET == "C19"] <- "C19 - Neoplasia Maligna da Junção Retossigmóide"
  df$LOCTUDET[df$LOCTUDET == "C20"] <- "C20 - Neoplasia Maligna do Reto"
  df$LOCTUDET[df$LOCTUDET == "C21"] <- "C21 - Neoplasia Maligna do Ânus e do Canal Anal"
  df$LOCTUDET[df$LOCTUDET == "C22"] <- "C22 - Neoplasia Maligna do Fígado e Das Vias Biliares Intra-hepáticas"
  df$LOCTUDET[df$LOCTUDET == "C23"] <- "C23 - Neoplasia Maligna da Vesícula Biliar"
  df$LOCTUDET[df$LOCTUDET == "C24"] <- "C24 - Neoplasia Maligna de Outras Partes, e de Partes Não Especificadas Das Vias Biliares"
  df$LOCTUDET[df$LOCTUDET == "C25"] <- "C25 - Neoplasia Maligna do Pâncreas"
  df$LOCTUDET[df$LOCTUDET == "C26"] <- "C26 - Neoplasia Maligna de Outros Órgãos Digestivos e de Localizações Mal Definidas no Aparelho Digestivo"
  df$LOCTUDET[df$LOCTUDET == "C30"] <- "C30 - Neoplasia Maligna da Cavidade Nasal e do Ouvido Médio"
  df$LOCTUDET[df$LOCTUDET == "C31"] <- "C31 - Neoplasia Maligna Dos Seios da Face"
  df$LOCTUDET[df$LOCTUDET == "C32"] <- "C32 - Neoplasia Maligna da Laringe"
  df$LOCTUDET[df$LOCTUDET == "C33"] <- "C33 - Neoplasia Maligna da Traquéia"
  df$LOCTUDET[df$LOCTUDET == "C34"] <- "C34 - Neoplasia Maligna Dos Brônquios e Dos Pulmões"
  df$LOCTUDET[df$LOCTUDET == "C37"] <- "C37 - Neoplasia Maligna do Timo"
  df$LOCTUDET[df$LOCTUDET == "C38"] <- "C38 - Neoplasia Maligna do Coração, Mediastino e Pleura"
  df$LOCTUDET[df$LOCTUDET == "C39"] <- "C39 - Neoplasia Maligna de Outras Localizações e de Localizações Mal Definidas do Aparelho Respiratório e Dos Órgãos Intratorácicos"
  df$LOCTUDET[df$LOCTUDET == "C40"] <- "C40 - Neoplasia Maligna Dos Ossos e Cartilagens Articulares Dos Membros"
  df$LOCTUDET[df$LOCTUDET == "C41"] <- "C41 - Neoplasia Maligna Dos Ossos e Das Cartilagens Articulares de Outras Localizações e de Localizações Não Especificadas"
  df$LOCTUDET[df$LOCTUDET == "C43"] <- "C43 - Melanoma Maligno da Pele"
  df$LOCTUDET[df$LOCTUDET == "C44"] <- "C44 - Outras Neoplasias Malignas da Pele"
  df$LOCTUDET[df$LOCTUDET == "C45"] <- "C45 - Mesotelioma"
  df$LOCTUDET[df$LOCTUDET == "C46"] <- "C46 - Sarcoma de Kaposi"
  df$LOCTUDET[df$LOCTUDET == "C47"] <- "C47 - Neoplasia Maligna Dos Nervos Periféricos e do Sistema Nervoso Autônomo"
  df$LOCTUDET[df$LOCTUDET == "C48"] <- "C48 - Neoplasia Maligna Dos Tecidos Moles do Retroperitônio e do Peritônio"
  df$LOCTUDET[df$LOCTUDET == "C49"] <- "C49 - Neoplasia Maligna do Tecido Conjuntivo e de Outros Tecidos Moles"
  df$LOCTUDET[df$LOCTUDET == "C50"] <- "C50 - Neoplasia Maligna da Mama"
  df$LOCTUDET[df$LOCTUDET == "C51"] <- "C51 - Neoplasia Maligna da Vulva"
  df$LOCTUDET[df$LOCTUDET == "C52"] <- "C52 - Neoplasia Maligna da Vagina"
  df$LOCTUDET[df$LOCTUDET == "C53"] <- "C53 - Neoplasia Maligna do Colo do Útero"
  df$LOCTUDET[df$LOCTUDET == "C54"] <- "C54 - Neoplasia Maligna do Corpo do Útero"
  df$LOCTUDET[df$LOCTUDET == "C55"] <- "C55 - Neoplasia Maligna do Útero, Porção Não Especificada"
  df$LOCTUDET[df$LOCTUDET == "C56"] <- "C56 - Neoplasia Maligna do Ovário"
  df$LOCTUDET[df$LOCTUDET == "C57"] <- "C57 - Neoplasia Maligna de Outros Órgãos Genitais Femininos e Dos Não Especificados"
  df$LOCTUDET[df$LOCTUDET == "C58"] <- "C58 - Neoplasia Maligna da Placenta"
  df$LOCTUDET[df$LOCTUDET == "C60"] <- "C60 - Neoplasia Maligna do Pênis"
  df$LOCTUDET[df$LOCTUDET == "C61"] <- "C61 - Neoplasia Maligna da Próstata"
  df$LOCTUDET[df$LOCTUDET == "C62"] <- "C62 - Neoplasia Maligna Dos Testículos"
  df$LOCTUDET[df$LOCTUDET == "C63"] <- "C63 - Neoplasia Maligna de Outros Órgãos Genitais Masculinos e Dos Não Especificados"
  df$LOCTUDET[df$LOCTUDET == "C64"] <- "C64 - Neoplasia Maligna do Rim, Exceto Pelve Renal"
  df$LOCTUDET[df$LOCTUDET == "C65"] <- "C65 - Neoplasia Maligna da Pelve Renal"
  df$LOCTUDET[df$LOCTUDET == "C66"] <- "C66 - Neoplasia Maligna Dos Ureteres"
  df$LOCTUDET[df$LOCTUDET == "C67"] <- "C67 - Neoplasia Maligna da Bexiga"
  df$LOCTUDET[df$LOCTUDET == "C68"] <- "C68 - Neoplasia Maligna de Outros Órgãos Urinários e Dos Não Especificados"
  df$LOCTUDET[df$LOCTUDET == "C69"] <- "C69 - Neoplasia Maligna do Olho e Anexos"
  df$LOCTUDET[df$LOCTUDET == "C70"] <- "C70 - Neoplasia Maligna Das Meninges"
  df$LOCTUDET[df$LOCTUDET == "C71"] <- "C71 - Neoplasia Maligna do Encéfalo"
  df$LOCTUDET[df$LOCTUDET == "C72"] <- "C72 - Neoplasia Maligna da Medula Espinhal, Dos Nervos Cranianos e de Outras Partes do Sistema Nervoso Central"
  df$LOCTUDET[df$LOCTUDET == "C73"] <- "C73 - Neoplasia Maligna da Glândula Tireóide"
  df$LOCTUDET[df$LOCTUDET == "C74"] <- "C74 - Neoplasia Maligna da Glândula Supra-renal (Glândula Adrenal)"
  df$LOCTUDET[df$LOCTUDET == "C75"] <- "C75 - Neoplasia Maligna de Outras Glândulas Endócrinas e de Estruturas Relacionadas"
  df$LOCTUDET[df$LOCTUDET == "C76"] <- "C76 - Neoplasia Maligna de Outras Localizações e de Localizações Mal Definidas"
  df$LOCTUDET[df$LOCTUDET == "C77"] <- "C77 - Neoplasia Maligna Secundária e Não Especificada Dos Gânglios Linfáticos"
  df$LOCTUDET[df$LOCTUDET == "C78"] <- "C78 - Neoplasia Maligna Secundária Dos Órgãos Respiratórios e Digestivos"
  df$LOCTUDET[df$LOCTUDET == "C79"] <- "C79 - Neoplasia Maligna Secundária de Outras Localizações"
  df$LOCTUDET[df$LOCTUDET == "C80"] <- "C80 - Neoplasia Maligna, Sem Especificação de Localização"
  df$LOCTUDET[df$LOCTUDET == "C81"] <- "C81 - Doença de Hodgkin"
  df$LOCTUDET[df$LOCTUDET == "C82"] <- "C82 - Linfoma Não-Hodgkin, Folicular (nodular)"
  df$LOCTUDET[df$LOCTUDET == "C83"] <- "C83 - Linfoma Não-Hodgkin Difuso"
  df$LOCTUDET[df$LOCTUDET == "C84"] <- "C84 - Linfomas de Células T Cutâneas e Periféricas"
  df$LOCTUDET[df$LOCTUDET == "C85"] <- "C85 - Linfoma Não-Hodgkin de Outros Tipos e de Tipo Não Especificado"
  df$LOCTUDET[df$LOCTUDET == "C88"] <- "C88 - Doenças Imunoproliferativas Malignas"
  df$LOCTUDET[df$LOCTUDET == "C90"] <- "C90 - Mieloma Múltiplo e Neoplasias Malignas de Plasmócitos"
  df$LOCTUDET[df$LOCTUDET == "C91"] <- "C91 - Leucemia Linfóide"
  df$LOCTUDET[df$LOCTUDET == "C92"] <- "C92 - Leucemia Mielóide"
  df$LOCTUDET[df$LOCTUDET == "C93"] <- "C93 - Leucemia Monocítica"
  df$LOCTUDET[df$LOCTUDET == "C94"] <- "C94 - Outras Leucemias de Células de Tipo Especificado"
  df$LOCTUDET[df$LOCTUDET == "C95"] <- "C95 - Leucemia de Tipo Celular Não Especificado"
  df$LOCTUDET[df$LOCTUDET == "C96"] <- "C96 - Outras Neoplasias Malignas e as Não Especificadas Dos Tecidos Linfático, Hematopoético e Tecidos Correlatos"
  df$LOCTUDET[df$LOCTUDET == "C97"] <- "C97 - Neoplasias Malignas de Localizações Múltiplas Independentes (prC97rias)"

  P <- ggplot(data=df, aes(x=LOCTUDET, y=NroCasos)) +
    geom_bar(stat="identity")

  P
}

numeroCasosLocalizacaoPrimaria(dfDados)
